// Free Website Program application handler.
// - Fires the GHL webhook (workflow trigger) with a flat payload whose keys
//   match the fieldKey suffixes we created under the folder
//   "Nanolix Free Website Program".
// - Also upserts the contact via GHL's Contacts API with the exact custom
//   field IDs so values land on the contact regardless of workflow config.
//
// Env: WEBHOOK_FREE_WEBSITE, GHL_LOCATIONID, GHL_PRIVATE_KEY (from .env.local)

const GHL_BASE = "https://services.leadconnectorhq.com";
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Field IDs generated by scripts/ghl-setup — keep in sync with GHL folder
// "Nanolix Free Website Program".
const FIELD_IDS = {
  business:    "oZKmk9NzrCMAdYWVmfvK",
  description: "mysph3Qp0pdSlA7H9t0Q",
  city:        "3vZ99n1X3g6gV11JCBMr",
  role:        "ai36SyAInCgZ6gOXWJ10",
  currentSite: "QuGQexJbcq4R2ACoKgJP",
  assets:      "CpzKybzSvs8rfQuGmVf7",
  goal:        "bxyUL3TIH6F4O7bSfQ1X",
  timeline:    "k7HR7ZgFGNvwIo0TnDsI",
};

export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed" });
  }

  const {
    business = "",
    email = "",
    description = "",
    city = "",
    role = "",
    currentSite = "",
    assets = "",
    goal = "",
    timeline = "",
  } = req.body || {};

  const trimmedEmail = String(email).trim();
  const trimmedBusiness = String(business).trim();
  if (!trimmedBusiness || !EMAIL_RE.test(trimmedEmail)) {
    return res.status(400).json({
      error: "Business name and a valid email are required.",
    });
  }

  const webhookUrl = process.env.WEBHOOK_FREE_WEBSITE;
  const locationId = process.env.GHL_LOCATIONID;
  const privateKey = process.env.GHL_PRIVATE_KEY;
  if (!webhookUrl || !locationId || !privateKey) {
    return res.status(500).json({ error: "GHL integration is not configured." });
  }

  // Flat payload keys match the GHL fieldKeys (minus the "contact." prefix)
  // so the workflow attached to the webhook can reference them verbatim.
  const webhookPayload = {
    source: "Nanolix Free Website Program",
    submittedAt: new Date().toISOString(),
    email: trimmedEmail,
    business_name_and_website_if_you_have_one: trimmedBusiness,
    what_does_your_business_do_in_one_sentence: String(description).trim(),
    city_and_country: String(city).trim(),
    your_role: String(role).trim(),
    do_you_have_a_website_now_and_what_is_wrong_with_it: String(currentSite).trim(),
    do_you_have_a_logo_photos_and_basic_content_ready: String(assets).trim(),
    the_number_one_thing_you_want_the_site_to_do: String(goal).trim(),
    how_soon_do_you_need_to_launch: String(timeline).trim(),
  };

  const upsertBody = {
    locationId,
    email: trimmedEmail,
    companyName: trimmedBusiness,
    source: "Nanolix Free Website Program",
    customFields: [
      { id: FIELD_IDS.business,    field_value: trimmedBusiness },
      { id: FIELD_IDS.description, field_value: webhookPayload.what_does_your_business_do_in_one_sentence },
      { id: FIELD_IDS.city,        field_value: webhookPayload.city_and_country },
      { id: FIELD_IDS.role,        field_value: webhookPayload.your_role },
      { id: FIELD_IDS.currentSite, field_value: webhookPayload.do_you_have_a_website_now_and_what_is_wrong_with_it },
      { id: FIELD_IDS.assets,      field_value: webhookPayload.do_you_have_a_logo_photos_and_basic_content_ready },
      { id: FIELD_IDS.goal,        field_value: webhookPayload.the_number_one_thing_you_want_the_site_to_do },
      { id: FIELD_IDS.timeline,    field_value: webhookPayload.how_soon_do_you_need_to_launch },
    ],
  };

  // Fire both in parallel — webhook triggers the workflow, upsert guarantees fields.
  const [webhookRes, contactRes] = await Promise.allSettled([
    fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(webhookPayload),
    }),
    fetch(`${GHL_BASE}/contacts/upsert`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${privateKey}`,
        Version: "2021-07-28",
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(upsertBody),
    }),
  ]);

  const errors = [];
  let webhookOk = false;
  if (webhookRes.status === "fulfilled" && webhookRes.value.ok) {
    webhookOk = true;
  } else {
    const detail = webhookRes.status === "fulfilled"
      ? `${webhookRes.value.status}: ${await webhookRes.value.text().catch(() => "")}`
      : webhookRes.reason?.message;
    errors.push(`webhook: ${detail}`);
  }

  let contactId = null;
  let contactOk = false;
  if (contactRes.status === "fulfilled" && contactRes.value.ok) {
    contactOk = true;
    try {
      const j = await contactRes.value.json();
      contactId = j.contact?.id || j.id || null;
    } catch {
      // Response wasn't JSON — still count as OK since status was 2xx.
    }
  } else {
    const detail = contactRes.status === "fulfilled"
      ? `${contactRes.value.status}: ${await contactRes.value.text().catch(() => "")}`
      : contactRes.reason?.message;
    errors.push(`contact upsert: ${detail}`);
  }

  if (!webhookOk && !contactOk) {
    return res.status(502).json({ error: "Submission failed. Please try again.", details: errors });
  }

  return res.status(200).json({ ok: true, webhookOk, contactOk, contactId, errors });
}
